spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres.cre2w8wkw34i.ap-southeast-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: admin123

  jpa:
    show-sql: false

  kafka:
    bootstrap-servers: student-kafka:9092

    consumer:
      group-id: student-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    student-topic: ${STUDENT_TOPIC:student-events-prod}